{{/*
   * Copyright 2024 EngFlow, Inc. All rights reserved.
   *
   * Licensed under the Apache License, Version 2.0 (the "License");
   * you may not use this file except in compliance with the License.
   * You may obtain a copy of the License at
   *
   *     http://www.apache.org/licenses/LICENSE-2.0
   *
   * Unless required by applicable law or agreed to in writing, software
   * distributed under the License is distributed on an "AS IS" BASIS,
   * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   * See the License for the specific language governing permissions and
   * limitations under the License.
   */}}

{{/*
  Check if the user has specified the "clusterUuid" input parameter, fail if not.

  The .Values object contains all user-specified input variables. Its schema is in "values.yaml".

  We insert the value into a Secret, which we then mount to the MyEngFlow Mini container and set the
  CLUSTER_UUID environment variable from.
  */}}
{{- if not .Values.clusterUuid.fromValue.value }}
  {{- fail "Run Helm with --set-string \"clusterUuid.fromValue.value=VALUE\" to specify the cluster UUID" }}
{{- end }}

---
apiVersion: "v1"
kind: Secret
metadata:
  name: "cluster-uuid"
data:
  "uuid.txt": {{ .Values.clusterUuid.fromValue.value | b64enc | quote }}
